pool:
  vmImage: 'VS2017-Win2016'

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
  #SeedWork
  SeedWorkVersion: '1.0.1'
  SeedWorkPushToNuget: False
  #Exceptions
  ExceptionsVersion: '1.0.1'
  ExceptionsPushToNuget: False
  #Domain.BR
  DomainBRVersion: '1.0.1'
  DomainBRPushToNuget: False
  #Identity.Abstractions
  IdentityAbstractionsVersion: '1.0.0'
  IdentityAbstractionsPushToNuget: False

steps:
# Install NuGet Tool
- task: NuGetToolInstaller@0
  displayName: Install NuGet Tool

# Restore NuGet packages
- task: NuGetCommand@2
  displayName: Restore NuGet Packages
  inputs:
    restoreSolution: '$(solution)'

# Build solution
- task: VSBuild@1
  displayName: Build Solution
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Run unit tests
- task: VSTest@2
  displayName: Run Unit Tests
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'

# Prepare publish files
- task: DotNetCoreCLI@2
  displayName: Prepare Publish Files
  inputs:
    command: publish
    publishWebProjects: False
    projects: '**/**/Furiza.Base.Core.*.csproj'
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: False

# Publish the artifacts
- task: PublishBuildArtifacts@1
  displayName: Publish Artifacts

# Publish Furiza.Base.Core.SeedWork to NuGet.org
- task: DotNetCoreCLI@2
  displayName: Pack Furiza.Base.Core.SeedWork
  condition: eq(variables['SeedWorkPushToNuget'], 'True')
  inputs:
    command: pack
    packagesToPack: '**/**/Furiza.Base.Core.SeedWork.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: SeedWorkVersion
- task: NuGetCommand@2
  displayName: Push Furiza.Base.Core.SeedWork to NuGet.org
  condition: eq(variables['SeedWorkPushToNuget'], 'True')
  continueOnError: True
  inputs:
    command: push
    nuGetFeedType: external
    packagesToPush: '$(build.artifactStagingDirectory)/Furiza.Base.Core.SeedWork.*.nupkg'
    publishFeedCredentials: 'apikey-nuget-core-seedwork'

# Publish Furiza.Base.Core.Exceptions to NuGet.org
- task: DotNetCoreCLI@2
  displayName: Pack Furiza.Base.Core.Exceptions
  condition: eq(variables['ExceptionsPushToNuget'], 'True')
  inputs:
    command: pack
    packagesToPack: '**/**/Furiza.Base.Core.Exceptions.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: ExceptionsVersion
- task: NuGetCommand@2
  displayName: Push Furiza.Base.Core.Exceptions to NuGet.org
  condition: eq(variables['ExceptionsPushToNuget'], 'True')
  continueOnError: True
  inputs:
    command: push
    nuGetFeedType: external
    packagesToPush: '$(build.artifactStagingDirectory)/Furiza.Base.Core.Exceptions.*.nupkg'
    publishFeedCredentials: 'apikey-nuget-core-exceptions'

# Publish Furiza.Base.Core.Domain.BR to NuGet.org
- task: DotNetCoreCLI@2
  displayName: Pack Furiza.Base.Core.Domain.BR
  condition: eq(variables['DomainBRPushToNuget'], 'True')
  inputs:
    command: pack
    packagesToPack: '**/**/Furiza.Base.Core.Domain.BR.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: DomainBRVersion
- task: NuGetCommand@2
  displayName: Push Furiza.Base.Core.Domain.BR to NuGet.org
  condition: eq(variables['DomainBRPushToNuget'], 'True')
  continueOnError: True
  inputs:
    command: push
    nuGetFeedType: external
    packagesToPush: '$(build.artifactStagingDirectory)/Furiza.Base.Core.Domain.BR.*.nupkg'
    publishFeedCredentials: 'apikey-nuget-core-domain.br'

# Publish Furiza.Base.Core.Identity.Abstractions to NuGet.org
- task: DotNetCoreCLI@2
  displayName: Pack Furiza.Base.Core.Identity.Abstractions
  condition: eq(variables['IdentityAbstractionsPushToNuget'], 'True')
  inputs:
    command: pack
    packagesToPack: '**/**/Furiza.Base.Core.Identity.Abstractions.csproj'
    versioningScheme: byEnvVar
    versionEnvVar: IdentityAbstractionsVersion
- task: NuGetCommand@2
  displayName: Push Furiza.Base.Core.Identity.Abstractions to NuGet.org
  condition: eq(variables['IdentityAbstractionsPushToNuget'], 'True')
  continueOnError: True
  inputs:
    command: push
    nuGetFeedType: external
    packagesToPush: '$(build.artifactStagingDirectory)/Furiza.Base.Core.Identity.Abstractions.*.nupkg'
    publishFeedCredentials: 'apikey-nuget-core-identity.abstractions'
